### ISSUE TITLE
Currency Selector

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#10]
the currency selector is not showing in the header or the menu

**URL tested:** https://beatnik-01.myshopify.com/pages/our-story

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Four-story&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/our-story) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/913a023c32972986c70ef4bd2b654974d5d7c6ed/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/913a023c32972986c70ef4bd2b654974d5d7c6ed/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Four-story&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/our-story) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved - put it in mobile menu w/ language selector

![screen shot 2019-02-11 at 12 41 13](https://user-images.githubusercontent.com/11278647/52563805-586b1f00-2dfa-11e9-928e-81022e8d6171.png)

**Comment by adstr123** [comment]
Resolved - put it in mobile menu w/ language selector

![screen shot 2019-02-11 at 12 41 13](https://user-images.githubusercontent.com/11278647/52563805-586b1f00-2dfa-11e9-928e-81022e8d6171.png)
