### ISSUE TITLE
Vegabonds page

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#11]
The image should reduce to be 25% width and the text 75% width so the text is readable on mobile

**URL tested:** https://beatnik-01.myshopify.com/pages/vagabonds

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Fvagabonds&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/vagabonds) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/1c1544d4e168572e596d9118ddc623910e345549/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/1c1544d4e168572e596d9118ddc623910e345549/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Fvagabonds&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/vagabonds) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved - redesigned Vagabond profile panels on mobile so no image is shown, just text. Image takes up too much room and not really necessary given there are images on the main page.
