### ISSUE TITLE
Vagabond panel - close button obstructed by cart drawer button

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#12]
Hard to show but when I opened the panel and tried to close it it opened up the shopping cart not closed the panel.

It seems like if the panel is open and you scroll up the menu moves into place but is hidden and then the cart icon is clickable.

**URL tested:** https://beatnik-01.myshopify.com/pages/vagabonds

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Fvagabonds&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/vagabonds) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/b7f60defd63294531c9cd141193eb1336d12a199/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/b7f60defd63294531c9cd141193eb1336d12a199/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Fvagabonds&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/vagabonds) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved - reduced header `z-index` property when panels are opened.

**Comment by adstr123** [comment]
Resolved - reduced header `z-index` property when panels are opened.
