### ISSUE TITLE
contact page

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#13]
Seems weird to have a contact form that emails Beatnik and some text saying, if you dont want to email us... email us.... is it supposed to be a phone number in the text?

**URL tested:** https://beatnik-01.myshopify.com/pages/contact

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Fcontact&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/contact) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/a4c0e9436feb046b7807040d82bd2c6f8684d170/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/a4c0e9436feb046b7807040d82bd2c6f8684d170/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Fcontact&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/contact) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
This seemed odd to me as well but the sentence has featured throughout several iterations of the copy they've sent, even after the contact page with a form went live... Maybe we should just remove it and see if they flag it up? @JoeCory

**Comment by adstr123** [comment]
Ignored it on multiple review calls, guessing this is how they want it so closing.
