### ISSUE TITLE
Product details tabs

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#15]
The tabs are breaking onto 2 lines here

**URL tested:** https://beatnik-01.myshopify.com/products/cloudy-whiskey

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fproducts%2Fcloudy-whiskey&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/products/cloudy-whiskey) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 |
| Browser | Mobile_chrome |
| Operating System | iOS 11.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/fcd90819ea8e991a346e97203e02ec4e162a2bb2/realios_iPhone_8.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/fcd90819ea8e991a346e97203e02ec4e162a2bb2/realios_iPhone_8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fproducts%2Fcloudy-whiskey&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/products/cloudy-whiskey) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
No longer an issue - products page redesigned with only two tabs, details moved up above form
