### ISSUE TITLE
Nav - increase padding beneath search bar

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#16]
search bar is very close to the bottom of the screen, needs some padding under it

**URL tested:** https://beatnik-01.myshopify.com/pages/faqs

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Ffaqs&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/faqs) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 |
| Browser | Mobile_chrome |
| Operating System | iOS 11.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/733c10a9eb230123cbdfef646a3273aadd5a72bb/realios_iPhone_8.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/733c10a9eb230123cbdfef646a3273aadd5a72bb/realios_iPhone_8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fpages%2Ffaqs&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/pages/faqs) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved w/ CSS
