### ISSUE TITLE
stockists - Sometimes scroll hover state effect doesn't work

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#17]
On desktop, each store card has a hover state that reveals an image of the store as the card background, and changes the text from black to white.

On mobile, this has been adapted so that as you scroll down the page, these hover states should become active one by one down the page as you scroll.

Sometimes, seemingly intermittently, this does not happen - much like when you don't wrap some JS in document.addEventListener("DOMContentLoaded", (event) => { // some function here });

**URL tested:** https://beatnik-01.myshopify.com/

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=9.0&device=Google+Pixel+2&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Google Pixel 2 |
| Browser | Mobile_chrome |
| Operating System | Android 9.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.74 in - 2.74 x 5.0 in |
| Viewport | 411 x 731 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d8c2930da8c14c4dc9b1aee35f7421a9f02903d0/realdroid_Google_Pixel_2.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/d8c2930da8c14c4dc9b1aee35f7421a9f02903d0/realdroid_Google_Pixel_2.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=9.0&device=Google+Pixel+2&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
@JoeCory Mind taking a look at this when you get the chance?

**Comment by JoeCory** [comment]
@adstr123  So my theory on the stockists issue is that the scrolling only triggers when the page loads up and is small right? i.e. on mobile?

but does not work if you drag the screen from large to small... so maybe you need some code to activate on screen width change to see if it should start running the mobile version code or not?
that might just give it another check to make sure that when it loads up on mobile, even if it does a weird glitch load and is massive then scales down it still works?

**Comment by adstr123** [comment]
Window was starting out 1440 wide. `onresize` event didn't solve it. Moved `window.innerWidth` check inside `onscroll` event to fire multiple times before ever reaching the `.stockist-card` elements.
