### ISSUE TITLE
Home - text overflows container in Features slider slides

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#20]
**URL tested:** https://beatnik-01.myshopify.com/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+SE&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone SE |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 640 x 1136 px |
| Screen size | 4.0 in - 2.0 x 3.5 in |
| Viewport | 320 x 568 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/ea2ddda84adef8d686fccfffcb61007bfc8ba359/realios_iPhone_SE.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/ea2ddda84adef8d686fccfffcb61007bfc8ba359/realios_iPhone_SE.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+SE&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved by decreasing padding on detail text
