### ISSUE TITLE
[iPhone only] Text inside 'Vagabonds' button breaks awkwardly

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#23]
**URL tested:** https://beatnik-01.myshopify.com/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5fcd494e571ab77e53e1910fea20ec1863d06800/realios_iPhone_8.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/5fcd494e571ab77e53e1910fea20ec1863d06800/realios_iPhone_8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved by decreasing button padding relative to grey container
