### ISSUE TITLE
Image overlapping

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#4]
Is this image meant to be overlapping?

**URL tested:** https://beatnik-01.myshopify.com/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/f8ae8bf3f7dc1ed0a3cd430ec180b7c322d0c6c1/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/f8ae8bf3f7dc1ed0a3cd430ec180b7c322d0c6c1/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Yes! On desktop it overlaps to the side and is a bit more obvious, on mobile it doesn't look as cool but still works I think. Going to keep it for now.
