### ISSUE TITLE
Mobile menu too large & forces scrolling

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#5]
Mobile menu links span off the page, either need to reduce padding and or put the login/faq into rows of 2?

**URL tested:** https://beatnik-01.myshopify.com/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c2f2bcdbed9e3414397a01e7ea4c73b0738b4de4/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/c2f2bcdbed9e3414397a01e7ea4c73b0738b4de4/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Menu has since grown inside further and is too large to fit without scrolling - may look at adding scroll indicator or other UI feedback during final review
