### ISSUE TITLE
Quantity selector

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#6]
Could add  an arrow or some form of indication to suggest you can click on this area to select more than one quantity. 

**URL tested:** https://beatnik-01.myshopify.com/products/moroccan-brown

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fproducts%2Fmoroccan-brown&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/products/moroccan-brown) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/f67ee99a74302686fbb9f3163bd0a675be74c976/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/f67ee99a74302686fbb9f3163bd0a675be74c976/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fproducts%2Fmoroccan-brown&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/products/moroccan-brown) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved - quantity selector has been removed in later revisions of the product page design.
