### ISSUE TITLE
'added to cart' text

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#7]
This could do with some more padding under it

**URL tested:** https://beatnik-01.myshopify.com/products/moroccan-brown

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fproducts%2Fmoroccan-brown&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/products/moroccan-brown) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/6bcc2ec31fcdbdff0bf840237ee9bffbcf85ddbf/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/6bcc2ec31fcdbdff0bf840237ee9bffbcf85ddbf/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Fproducts%2Fmoroccan-brown&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/products/moroccan-brown) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved - theme bug. `margin-bottom` was being overridden by `normalize.css`

**Comment by adstr123** [comment]
Resolved - theme bug. `margin-bottom` was being overridden by `normalize.css`
