### ISSUE TITLE
Account page - button at bottom merges with footer

### ISSUE THREAD

**Issue by JoeCory** [noughtsandonesdev/beatnik#8]
the page needs more padding at the bottom, atm the button merges with the footer.

**URL tested:** https://beatnik-01.myshopify.com/account/register

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Faccount%2Fregister&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/account/register) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 3.07 x 6.24 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8eb096ba3feb263dc6ced0dee7f04cdffce2bc45/realios_iPhone_8_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/8eb096ba3feb263dc6ced0dee7f04cdffce2bc45/realios_iPhone_8_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8+Plus&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fbeatnik-01.myshopify.com%2Faccount%2Fregister&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://beatnik-01.myshopify.com/account/register) to reproduce the issue on Browserstack**

**Comment by adstr123** [comment]
Resolved w/ CSS
